### ISSUE TITLE
[FEATURE REQUEST]: Adding Development Branch to Project

### ISSUE THREAD

**Issue by kodbilenadam** [iamhectorsosa/screenshot#20]
**Description**:
As part of project management strategy, I propose adding a development branch to our GitHub repository. This issue aims to outline the benefits of implementing a development branch and guide the necessary steps to incorporate it into our workflow.

**Benefits of Adding a Development Branch**:
1. Isolation of Unstable Code:
   By introducing a dedicated development branch, we can segregate unstable code from the main branch. This allows developers to work on new features, bug fixes, and experiments without affecting the stability of the main branch. It ensures that only thoroughly tested and reviewed code is merged into the main branch, reducing the chances of introducing bugs or breaking functionality.

2. Collaborative Code Integration:
   With a development branch, multiple developers can collaborate on a specific feature or task without interfering with each other's work. Each developer can create a separate branch from the development branch, work independently, and then merge their changes back into the development branch. This promotes parallel development and smoother collaboration between team members.

3. Early Detection of Integration Issues:
   By merging changes into the development branch, we can identify and resolve integration issues at an early stage. Frequent integration of code from various developers allows us to catch conflicts, compatibility problems, or any issues arising from the interaction of different code components. This leads to quicker bug identification and resolution, reducing the risk of encountering major issues during the final integration with the main branch.

4. Facilitates Testing and Continuous Integration:
   The development branch provides an ideal environment for testing new features and changes. By merging code into the development branch, we can execute automated tests, conduct code reviews, and perform integration testing in a controlled manner. This helps ensure that the changes made by developers are functional, compatible, and aligned with the project's quality standards before merging into the main branch.

5. Incremental and Controlled Releases:
   With a development branch, we can adopt a more incremental and controlled release process. Completed and tested features can be merged into the development branch, allowing stakeholders and users to review and provide feedback on individual features. It also provides an opportunity to collect valuable feedback before merging the changes into the main branch and deploying them to production.

**Steps to Implement**:
1. Create a new branch named "development" based on the current state of the main branch.
2. Update the project documentation to reflect the new branch and its purpose.
3. Update the development workflow and branching strategy to incorporate the development branch.
4. Establish guidelines for code reviews, automated tests, and merging into the development branch.
5. Monitor the development branch regularly, resolve conflicts, conduct integration tests, and ensure the stability of the branch.
6. Periodically merge stable and tested features from the development branch into the main branch following the established release schedule or criteria.

**Comment by ekqt** [comment]
@kodbilenadam What I really don't like about Git Flow branching strategy is that we always need to be merging back from main into development. I think that will slow us down dramatically and the value we get from it wouldn't be worth it with a project/team this size. 

If we were to use a main (production, development, release and feature branches. I'm guessing we need to branch out of development once we're ready to release. Merge release onto main and then merge main onto development to keep our development branch updated. Here are the biggest cons:

- We need to gather several features and the developers will have to wait until we are ready to create a release
- Once we push a release to main (production) we also need to update main back onto development branch
- Potential merge conflicts along the way will slow us down as well

Don't get me wrong, I think there are good benefits in having this branching strategy, I just don't think they overcome its cons. I think that with Vercel's preview builds on each feature branch and using the current GitHub flow branching strategy should be good enough for our project at the time being.

I'm opening in discussing this, but if we don't have a clear way on how we could make this easier. I would rather not.

On a separate note, maybe we can figure out how to set up a workflow for tagged releases.

**Comment by iamhectorsosa** [comment]
Closing due to being inactive
